name: Update M3U Playlist

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir çalıştır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run M3U merge script
        run: python playlist_creator.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Kanal listesi güncellendi." || echo "No changes to commit"
          git push
